### ISSUE TITLE
Broken anchor LNO: 191

### ISSUE THREAD

**Issue by jennfshr** [ovis-hpc/readthedocs#6]
This link doesn't work to find the right anchor, probably because there's two "Test The Darshan-LDMS Integrated Code" sections, but both have a qualifier in the name:
Test the Darshan-LDMS Integrated Code (Multi Node)
Test the Darshan-LDMS Integrated Code (Single Node)

![image](https://github.com/ovis-hpc/readthedocs/assets/850386/4730043a-b9e1-48f2-a785-7163bb6fe229)

I'm editing this to point to the multi-node section, but this likely could use some review, and perhaps a refactoring to have a top level section named "Test the Darshan-LDMS Integrated Code" that contains both single and multi-node instructions.

**Comment by spwalto** [comment]
@jennfshr I just noticed that you didn’t have write access to this repo (I.e. why you weren’t able to do your own push requests without approval). This should be fixed now so you can test out the links and RTD compilation whenever you want/need to. 

Also, you may need to refresh your browser if the changes are not immediately showing up in the RTD.

**Comment by jennfshr** [comment]
Great! Thanks, it appears to have worked to fix that broken link.

Appreciate your help!

😊

Jen

From: Sara W ***@***.***>
Date: Tuesday, April 30, 2024 at 5:36 PM
To: ovis-hpc/readthedocs ***@***.***>
Cc: Green, Jennifer Kathleen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ovis-hpc/readthedocs] Broken anchor LNO: 191 (Issue #6)

@jennfshr<https://github.com/jennfshr> Also, I just noticed that you didn’t have write access which is why you weren’t able to do your own push requests without approval. There should be fixed now, so you can test out the links and RTD compilation whenever you want/need to.

Also, you may need to refresh your browser if the changes are not immediately showing up in the RTD.
