### ISSUE TITLE
Fix build instructions to not include Python 2.7 references

### ISSUE THREAD

**Issue by jennfshr** [ovis-hpc/readthedocs#8]
And generally update with new configure options, and ensure no outdated instructions are included.

@tom95858

**Comment by tom95858** [comment]
@jennfshr  also could we please have someone try these instructions and confirm that they work. The python2.7 reference was just an example. We should have whoever makes this change confirms that it works on a naked install of RHEL ?

**Comment by spwalto** [comment]
@jennfshr I've created a new branch with the rhel9 build and installation instructions. 

There's not a lot of major changes so I'll won't merge until the Ubuntu patch is done and will make the necessary updates so nothing is overwritten.

**Comment by jennfshr** [comment]
> @jennfshr I've created a new branch with the rhel9 build and installation instructions.
> 
> There's not a lot of major changes so I'll won't merge until the Ubuntu patch is done and will make the necessary updates so nothing is overwritten.

I've looked through your changes, and don't see anything I can't just merge into my working fork, probably just need to deal with a couple minor conflicts.  Please just go ahead and merge when you're done, and I'll update mine to pull your changes in.  @Snell1224
